[package]
name = "hole-punchky-client"
description = "Native Hole Punchky client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
futures-util.workspace = true
hole-punchky-protocol = { path = "../protocol" }
iroh.workspace = true
n0-watcher.workspace = true
pubky.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
hole-punchky-rendezvous = { path = "../rendezvous" }
iroh-relay = { version = "=1.1.0", default-features = false, features = ["server", "tls-ring"] }

[lints]
workspace = true
