[package]
name = "hole-punchky-protocol"
description = "Signed and encrypted wire protocol for Hole Punchky"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
base64.workspace = true
ed25519-dalek.workspace = true
hpke.workspace = true
pubky-common.workspace = true
serde.workspace = true
serde_jcs.workspace = true
serde_json.workspace = true
thiserror.workspace = true
url.workspace = true
uuid.workspace = true
zeroize.workspace = true

[lints]
workspace = true
